#pragma once

#include <JuceHeader.h>
#include <cmath>

/**
 * @file Oscillator.h
 * @brief Implements a band-limited digital oscillator supporting sine,
 *        square, sawtooth, and triangle waveforms.
 *
 * Anti-aliased square and sawtooth waveforms are generated using the
 * Polynomial Band-Limited Step (PolyBLEP) technique, which smooths waveform
 * discontinuities to reduce aliasing while maintaining low computational cost.
 *
 * The oscillator forms the primary sound source for each synthesis voice and
 * is designed for real-time polyphonic operation.
 */

 /**
  * Generates band-limited oscillator waveforms for the synthesiser engine.
  *
  * Supported waveforms:
  *   1. Sine
  *   2. Square (PolyBLEP corrected)
  *   3. Sawtooth (PolyBLEP corrected)
  *   4. Triangle (generated by integrating a corrected square wave)
  *
  * Phase is represented as a normalised value in the range [0,1), allowing
  * waveform generation to remain independent of the current sample rate.
  */
class Oscillator
{
public:

    /**
     * Updates the operating sample rate and recalculates the phase increment.
     *
     * @param newSampleRate Active host sample rate in hertz.
     */
    void setSampleRate(double newSampleRate)
    {
        sampleRate = newSampleRate;
        updatePhaseDelta();
    }

    /**
     * Updates oscillator frequency.
     *
     * @param newFrequency Oscillator frequency in hertz.
     */
    void setFrequency(double newFrequency)
    {
        frequency = newFrequency;
        updatePhaseDelta();
    }

    /**
     * Selects the waveform generated by the oscillator.
     *
     * @param newWaveform Integer waveform identifier.
     */
    void setWaveform(int newWaveform)
    {
        waveform = newWaveform;
    }

    /**
     * Generates the next oscillator sample.
     *
     * Waveforms containing discontinuities are corrected using PolyBLEP to
     * reduce aliasing before phase advancement occurs.
     *
     * @return One audio sample.
     */
    float getNextSample()
    {
        float output = 0.0f;

        switch (waveform)
        {
        case 1:     // Sine wave
            output = (float)std::sin(phase * 2.0 * juce::MathConstants<double>::pi);
            break;

        case 2:     // PolyBLEP square wave
        {
            output = phase < 0.5 ? 1.0f : -1.0f;

            // Apply correction at both waveform transitions.
            output += (float)polyBLEP(phase, phaseDelta);
            output -= (float)polyBLEP(std::fmod(phase + 0.5, 1.0), phaseDelta);

            break;
        }

        case 3:     // PolyBLEP sawtooth wave
        {
            output = (float)(2.0 * phase - 1.0);

            // Correct the discontinuity occurring at phase wrap-around.
            output -= (float)polyBLEP(phase, phaseDelta);

            break;
        }

        case 4:     // Triangle wave
        {
            // Generate a corrected square wave prior to integration.
            float square = phase < 0.5 ? 1.0f : -1.0f;

            square += (float)polyBLEP(phase, phaseDelta);
            square -= (float)polyBLEP(std::fmod(phase + 0.5, 1.0), phaseDelta);

            // A leaky integrator converts the square wave into a stable
            // triangle waveform while preventing long-term DC accumulation.
            triangleAccumulator =
                (float)(phaseDelta * 4.0) * square
                + (1.0f - (float)(phaseDelta * 0.1)) * triangleAccumulator;

            output = triangleAccumulator;
            break;
        }

        default:
            output = (float)std::sin(phase * 2.0 * juce::MathConstants<double>::pi);
            break;
        }

        // Advance the oscillator phase and wrap into the normalised range.
        phase += phaseDelta;

        if (phase >= 1.0)
            phase -= 1.0;

        return output;
    }

private:

    //==========================================================================
    // Oscillator state

    double sampleRate = 44100.0;
    double frequency = 440.0;

    // Normalised oscillator phase.
    double phase = 0.0;

    // Phase increment computed from frequency and sample rate.
    double phaseDelta = 0.0;

    // State used by the triangle-wave integrator.
    float triangleAccumulator = 0.0f;

    // Currently selected waveform.
    int waveform = 1;

    /**
     * Updates the phase increment following changes to frequency or sample
     * rate.
     */
    void updatePhaseDelta()
    {
        phaseDelta = frequency / sampleRate;
    }

    /**
     * Polynomial Band-Limited Step (PolyBLEP) correction function.
     *
     * PolyBLEP smooths waveform discontinuities over a single sample interval,
     * reducing aliasing without requiring oversampling or wavetable
     * interpolation.
     *
     * @param t  Current normalised phase.
     * @param dt Phase increment per sample.
     *
     * @return Polynomial correction applied at waveform discontinuities.
     */
    double polyBLEP(double t, double dt) const
    {
        // Beginning of the discontinuity.
        if (t < dt)
        {
            t /= dt;
            return t + t - t * t - 1.0;
        }

        // End of the discontinuity.
        else if (t > 1.0 - dt)
        {
            t = (t - 1.0) / dt;
            return t * t + t + t + 1.0;
        }

        // No correction required away from discontinuities.
        return 0.0;
    }
};