/**
 * @file Oscillator.h
 * @brief Implements a basic digital oscillator capable of generating multiple
 *        waveform types for the synthesiser.
 *
 * The oscillator maintains a continuously advancing phase accumulator and
 * produces one audio sample per call. Waveforms are generated procedurally
 * from the current phase, allowing the same oscillator architecture to
 * produce sine, square, sawtooth, and triangle waves.
 */

#pragma once

#include <JuceHeader.h>

 /**
  * Generates periodic audio waveforms for the synthesis engine.
  *
  * The oscillator stores frequency and phase independently so that waveform
  * generation remains continuous between successive samples. The oscillator
  * does not perform amplitude shaping, filtering, or modulation directly;
  * these processes are handled elsewhere in the synthesis pipeline.
  */
class Oscillator
{
public:
    /**
     * Sets the audio sample rate used to calculate phase progression.
     *
     * @param newSampleRate Active audio sample rate in hertz.
     */
    void setSampleRate(double newSampleRate)
    {
        sampleRate = newSampleRate;
        updateAngleDelta();
    }

    /**
     * Sets the oscillator frequency.
     *
     * @param newFrequency Oscillation frequency in hertz.
     */
    void setFrequency(double newFrequency)
    {
        frequency = newFrequency;
        updateAngleDelta();
    }

    /**
     * Selects the waveform generated by the oscillator.
     *
     * Supported waveforms:
     *  1. Sine
     *  2. Square
     *  3. Sawtooth
     *  4. Triangle
     *
     * @param newWaveform Waveform identifier.
     */
    void setWaveform(int newWaveform)
    {
        waveform = newWaveform;
    }

    /**
     * Generates one sample of the currently selected waveform.
     *
     * The current phase is converted into a normalised range before waveform
     * evaluation. After sample generation, the phase accumulator advances by
     * the precomputed phase increment ready for the next sample.
     *
     * @return One oscillator sample in the range -1.0 to +1.0.
     */
    float getNextSample()
    {
        float oscillatorValue = 0.0f;

        // Convert the phase accumulator into a normalised phase between
        // 0.0 and 1.0 for waveform generation.
        auto phase = currentAngle / (2.0 * juce::MathConstants<double>::pi);

        while (phase >= 1.0)
            phase -= 1.0;

        switch (waveform)
        {
        case 1:
            oscillatorValue = (float)std::sin(currentAngle);
            break;

        case 2:
            oscillatorValue = phase < 0.5 ? 1.0f : -1.0f;
            break;

        case 3:
            oscillatorValue = (float)((2.0 * phase) - 1.0);
            break;

        case 4:
            oscillatorValue = (float)(4.0 * std::abs(phase - 0.5) - 1.0);
            break;

        default:
            oscillatorValue = (float)std::sin(currentAngle);
            break;
        }

        // Advance the phase accumulator ready for the next generated sample.
        currentAngle += angleDelta;

        return oscillatorValue;
    }

private:
    //==========================================================================
    // Oscillator state

    double sampleRate = 44100.0;
    double frequency = 440.0;
    double currentAngle = 0.0;
    double angleDelta = 0.0;

    // Identifier of the waveform currently selected for generation.
    int waveform = 1;

    /**
     * Recalculates the phase increment from the current frequency and sample
     * rate.
     *
     * The phase increment determines how far the oscillator advances through
     * one cycle for each generated audio sample.
     */
    void updateAngleDelta()
    {
        angleDelta = frequency * 2.0 * juce::MathConstants<double>::pi / sampleRate;
    }
};